// ESLint baseline (flat config).
import js from "@eslint/js";
import { defineConfig, globalIgnores } from "eslint/config";
import reactHooks from "eslint-plugin-react-hooks";
import globals from "globals";
import tseslint from "typescript-eslint";
import tracklistPro from "./eslint-rules/no-raw-jsx-strings.js";

export default defineConfig([
  globalIgnores(["dist/", "src-tauri/", "spikes/", "archive/"]),
  {
    files: ["**/*.{ts,tsx,js,mjs}"],
    extends: [js.configs.recommended, tseslint.configs.recommended],
    languageOptions: {
      ecmaVersion: 2022,
      globals: globals.browser,
    },
  },
  {
    files: ["src/**/*.{ts,tsx}"],
    extends: [reactHooks.configs.flat.recommended],
  },
  {
    // User-visible text goes through i18next (ROADMAP 1.1, Language).
    // Tests are exempt: their fixtures never reach a user.
    files: ["src/**/*.{jsx,tsx}"],
    ignores: ["src/**/*.test.{jsx,tsx}"],
    plugins: { "tracklist-pro": tracklistPro },
    rules: {
      "tracklist-pro/no-raw-jsx-strings": "error",
    },
  },
  {
    // Generated by tauri-specta and never hand-edited (CLAUDE.md). Its
    // runtime helper for commands that return a Result casts with `any`.
    files: ["src/bindings.ts"],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
    },
  },
  {
    // CI helper scripts, build scripts and lint rules run in Node, not the browser.
    files: [".github/**/*.mjs", "scripts/**/*.mjs", "eslint-rules/**/*.js"],
    languageOptions: {
      globals: globals.node,
    },
  },
]);
