// Regenerate with `cargo run --example export_bindings` in src-tauri.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  Returns the app's name, version and bundle ID. */
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	/**
	 *  The key notation the user chose; Camelot until they choose one. The
	 *  frontend formats keys with it and the generated `KEY_NAMES` table.
	 */
	keyNotation: () => typedError<KeyNotation, IpcError>(__TAURI_INVOKE("key_notation")),
	/**  Sets the key notation for the whole app. */
	setKeyNotation: (notation: KeyNotation) => typedError<null, IpcError>(__TAURI_INVOKE("set_key_notation", { notation })),
	/**  Every queued and running job, for the Activity status to start from. */
	activity: () => typedError<ActivitySnapshot, IpcError>(__TAURI_INVOKE("activity")),
	/**  Cancels a queued or running job. */
	cancelJob: (id: JobId) => typedError<CancelOutcome, IpcError>(__TAURI_INVOKE("cancel_job", { id })),
	/**
	 *  Undoes the most recent operation, unless something it wrote has changed
	 *  since. If the undo hits an error, nothing was changed.
	 */
	undoLastOperation: () => typedError<UndoOutcome, IpcError>(__TAURI_INVOKE("undo_last_operation")),
	/**  Every music folder, oldest first. */
	musicFolders: () => typedError<MusicFolder[], IpcError>(__TAURI_INVOKE("music_folders")),
	/**  Adds a music folder. `role` defaults to scan. */
	addMusicFolder: (path: string, role: 
/**  Scanned into All music (the default). */
"scan" | 
/**  Watched for new arrivals (Phase 2, ROADMAP 2.1). */
"inbox" | null) => typedError<MusicFolder, IpcError>(__TAURI_INVOKE("add_music_folder", { path, role })),
	/**  Removes a music folder from the app. Its files stay on disk untouched. */
	removeMusicFolder: (id: MusicFolderId) => typedError<null, IpcError>(__TAURI_INVOKE("remove_music_folder", { id })),
	/**
	 *  Scans the music folders `ids`, or all of them. Returns the job's id; its
	 *  progress shows in Activity, and new files arrive as `ScannedFiles`.
	 */
	scanMusicFolders: (ids: MusicFolderId[] | null) => typedError<JobId, IpcError>(__TAURI_INVOKE("scan_music_folders", { ids })),
	/**
	 *  Turns a music folder's watcher on or off. On: the folder is rescanned
	 *  now and whenever files change under it. Off: it's scanned only when
	 *  asked.
	 */
	setMusicFolderWatch: (id: MusicFolderId, watch: boolean) => typedError<null, IpcError>(__TAURI_INVOKE("set_music_folder_watch", { id, watch })),
	/**
	 *  The rekordbox XML source: the chosen export, the watch, the last read or
	 *  failure and, with the watch on, a newer export to offer.
	 */
	rekordboxXmlSource: () => typedError<XmlSource, IpcError>(__TAURI_INVOKE("rekordbox_xml_source")),
	/**
	 *  Reads an export into the snapshot, as a job. With a `path` (the file
	 *  the user just picked, or a newer export offered), that file becomes the
	 *  chosen export once it's read; without one, the chosen export is read
	 *  again. Returns the job's id.
	 */
	readRekordboxXml: (path: string | null) => typedError<JobId, IpcError>(__TAURI_INVOKE("read_rekordbox_xml", { path })),
	/**  Turns the watch for newer exports on or off. */
	setRekordboxXmlWatch: (watch: boolean) => typedError<null, IpcError>(__TAURI_INVOKE("set_rekordbox_xml_watch", { watch })),
	/**
	 *  Whether the app may read (and so download) online-only files. Off until
	 *  the user turns it on.
	 */
	readOnlineOnlyFiles: () => typedError<boolean, IpcError>(__TAURI_INVOKE("read_online_only_files")),
	/**  Lets the app read online-only files, or stops it. */
	setReadOnlineOnlyFiles: (on: boolean) => typedError<null, IpcError>(__TAURI_INVOKE("set_read_online_only_files", { on })),
	/**
	 *  Hashes the files in the music folders `ids`, or in all of them, that
	 *  have no hashes yet or changed since they were hashed. Returns the job's
	 *  id; it runs in the background at low priority, and its progress shows
	 *  in Activity.
	 */
	hashMusicFolders: (ids: MusicFolderId[] | null) => typedError<JobId, IpcError>(__TAURI_INVOKE("hash_music_folders", { ids })),
	/**
	 *  Reads the files in the music folders `ids`, or in all of them. Returns
	 *  the job's id; its progress shows in Activity.
	 */
	readFiles: (ids: MusicFolderId[] | null) => typedError<JobId, IpcError>(__TAURI_INVOKE("read_files", { ids })),
	/**
	 *  Fingerprints every file that's due, in the background. Returns the
	 *  job's id; if a fingerprint job over every file is already queued or
	 *  running, returns that one instead of starting another.
	 */
	fingerprintFiles: () => typedError<JobId, IpcError>(__TAURI_INVOKE("fingerprint_files")),
	/**
	 *  Fingerprints `file_ids` before anything else: the tracks on screen.
	 *  A running fingerprint job takes them next; if none is running, a job
	 *  for just these starts at once, and its id is returned.
	 */
	fingerprintFirst: (fileIds: number[]) => typedError<number | null, IpcError>(__TAURI_INVOKE("fingerprint_first", { fileIds })),
};

/** Events */
export const events = {
	jobUpdates: makeEvent<JobUpdates>("job-updates"),
	scannedFiles: makeEvent<ScannedFiles>("scanned-files"),
	volumesChanged: makeEvent<VolumesChanged>("volumes-changed"),
};

/* Constants */
export const ERROR_KEYS = {"alreadyAdded":"musicFolders:alreadyAdded","badPath":"musicFolders:badPath","busy":"errors:busy","cannotWrite":"errors:cannotWrite","containsMusicFolder":"musicFolders:containsMusicFolder","damaged":"errors:damaged","database":"errors:database","diskFull":"errors:diskFull","insideMusicFolder":"musicFolders:insideMusicFolder","internal":"errors:internal","musicFolderInUse":"musicFolders:inUse","musicFolderNotFound":"musicFolders:notFound","noRekordboxXml":"rekordbox:error.noneChosen","notAFolder":"musicFolders:notAFolder","notRekordboxXml":"rekordbox:error.notAnExport","rekordboxXmlNotFound":"rekordbox:error.notFound","stopped":"errors:stopped"} as const;

export const KEY_NAMES = [{"names":["1A","2A","3A","4A","5A","6A","7A","8A","9A","10A","11A","12A","1B","2B","3B","4B","5B","6B","7B","8B","9B","10B","11B","12B"],"notation":"camelot"},{"names":["G#m","Ebm","Bbm","Fm","Cm","Gm","Dm","Am","Em","Bm","F#m","C#m","B","F#","Db","Ab","Eb","Bb","F","C","G","D","A","E"],"notation":"musical_standard"},{"names":["Abm","Ebm","Bbm","Fm","Cm","Gm","Dm","Am","Em","Bm","F#m","Dbm","B","F#","Db","Ab","Eb","Bb","F","C","G","D","A","E"],"notation":"musical_rekordbox"},{"names":["G#m","D#m","A#m","Fm","Cm","Gm","Dm","Am","Em","Bm","F#m","C#m","B","F#","C#","G#","D#","A#","F","C","G","D","A","E"],"notation":"musical_sharps"},{"names":["Abm","Ebm","Bbm","Fm","Cm","Gm","Dm","Am","Em","Bm","Gbm","Dbm","B","Gb","Db","Ab","Eb","Bb","F","C","G","D","A","E"],"notation":"musical_flats"}] as const;

/* Types */
/**
 *  Every queued and running job, and the `seq` of the last update already
 *  reflected in it.
 */
export type ActivitySnapshot = {
	seq: number,
	/**  Running jobs first, then queued; each in the order workers take them. */
	jobs: JobUpdate[],
};

/**  The app's name, version and bundle ID, as the frontend sees them. */
export type AppInfo = {
	name: string,
	version: string,
	identifier: string,
};

/**  What asking to cancel a job did. */
export type CancelOutcome = 
/**  It hadn't started, and now never will. */
"cancelled" | 
/**  It's running and will stop at its next check. */
"stopping" | 
/**  It had already finished, or there's no such job. */
"not_active";

export type ConflictProblem = 
/**  The field holds a different value from the one the operation left. */
"changedSince" | 
/**  The row the operation changed or made has been deleted since. */
"rowGone" | 
/**  The row the operation deleted exists again. */
"rowBack" | 
/**
 *  Other rows now reference the row, and undoing would silently delete
 *  or change them through a foreign key.
 */
"referenced";

/**
 *  What went wrong, in terms the user can act on. Each kind has one
 *  message in the locale files.
 */
export type ErrorKind = 
/**  The database was busy with another write for too long. */
"busy" | 
/**  The disk holding the app data folder is full. */
"diskFull" | 
/**  The app data folder can't be written (read-only, or no permission). */
"cannotWrite" | 
/**  The database file is damaged, or isn't a database. */
"damaged" | 
/**  Any other database failure. */
"database" | 
/**  The database writer has stopped; only a restart brings it back. */
"stopped" | 
/**  A bug or an impossible state: the app did something it shouldn't. */
"internal" | 
/**  The path given as a music folder isn't a folder that exists. */
"notAFolder" | 
/**
 *  The path can't be stored as a music folder: not a full path from a
 *  drive or share, a name Windows doesn't allow, or an unreadable drive.
 */
"badPath" | 
/**  That folder is already a music folder. */
"alreadyAdded" | 
/**  The folder is inside the existing music folder `musicFolder`. */
"insideMusicFolder" | 
/**  The folder contains the existing music folder `musicFolder`. */
"containsMusicFolder" | 
/**  There's no music folder with that id. */
"musicFolderNotFound" | 
/**
 *  Tracks, Library tracks or relinks still use files in the music
 *  folder, so it can't be removed.
 */
"musicFolderInUse" | 
/**  The rekordbox export isn't a file that exists. */
"rekordboxXmlNotFound" | 
/**  The file isn't a rekordbox collection export. */
"notRekordboxXml" | 
/**  No rekordbox export has been chosen yet. */
"noRekordboxXml";

/**
 *  A value filled into an error message: data (a name, a path, a count),
 *  never prose. Numbers stay numbers so the frontend formats them. They're
 *  32-bit whole numbers, so every one is exact in a TypeScript `number` and
 *  there's no NaN to send; add a finite decimal when a message needs one.
 */
export type ErrorParam = string | number;

/**  An export file found on disk. */
export type ExportFile = {
	path: string,
	/**  The file name, for showing. */
	name: string,
	/**  Milliseconds since the Unix epoch. */
	modifiedMs: number,
};

/**  Why a read failed, in terms the user can act on. */
export type FailureReason = 
/**  The file isn't there any more. */
"notFound" | 
/**  The file couldn't be opened or read. */
"cantRead" | 
/**  Not well-formed: cut off, or damaged. Export again. */
"damaged" | 
/**  Well-formed XML, but not a rekordbox collection export. */
"notAnExport";

/**
 *  Why a command failed, as the frontend receives it: a kind and the
 *  parameters its message needs. Never error text.
 */
export type IpcError = {
	kind: ErrorKind,
	params: { [key in string]: ErrorParam },
};

/**  A job's row id in the `job` table. */
export type JobId = number;

/**
 *  The kinds of background work (ROADMAP 0.1). Stored in `job.kind` as
 *  [`JobKind::as_str`].
 */
export type JobKind = 
/**  Walk the music folders for audio files (1.1). */
"scan" | 
/**  Read the files' tags and audio properties (1.1 stage 2). */
"read" | 
/**  Hash a file's audio (`audio_hash`). */
"hash" | 
/**  Acoustic fingerprint (1.4). */
"fingerprint" | 
/**  Estimate BPM, key and energy (3.7). */
"analyze" | 
/**  Run the audio model (3.8). */
"embed" | 
/**  Make a Library copy in another format (2.6). */
"convert" | 
/**  Write an export, e.g. the rekordbox XML (1.9). */
"export" | 
/**  Read rekordbox's XML export into the snapshot (1.2). */
"read_rekordbox";

/**
 *  Where a job is in its life. Stored in `job.status` as
 *  [`JobStatus::as_str`].
 */
export type JobStatus = 
/**  Waiting for a worker. */
"queued" | 
/**  A worker is doing it. */
"running" | 
/**  Finished its work. */
"done" | 
/**  Stopped with an error, kept in `job.error`. */
"failed" | 
/**  Stopped because it was cancelled. */
"cancelled";

/**
 *  A job changed: it was queued, started, made progress or finished.
 * 
 *  Every update carries `seq`, which rises by one with each change the app
 *  makes to any job. A listener that starts from an [`ActivitySnapshot`]
 *  applies only the updates newer than the snapshot's `seq`, and for each
 *  job only updates newer than the last it applied, so a job never goes
 *  back to an older state.
 */
export type JobUpdate = {
	seq: number,
	id: JobId,
	kind: JobKind,
	status: JobStatus,
	/**  0 to 1, once the job has reported any. */
	progress: number | null,
	/**  Higher runs first. */
	priority: number,
};

/**
 *  Job updates, sent together: the newest update for each job that
 *  changed since the last batch, in `seq` order.
 */
export type JobUpdates = JobUpdate[];

/**
 *  How keys are shown: one app-wide setting (ROADMAP §1.1), stored in the
 *  `setting` table (see `crate::settings`). Camelot is the default.
 * 
 *  To add a notation (e.g. Open Key, or Serato's or Mixed In Key's
 *  spellings): add a variant here and to [`KeyNotation::ALL`], and a match
 *  arm in [`MusicalKey::format`]. The stored name, the TypeScript type and
 *  the frontend's name table follow from those.
 */
export type KeyNotation = 
/**  `8A`, `12B`. */
"camelot" | 
/**
 *  Conventional key-signature spelling: the enharmonic name with the
 *  fewest sharps or flats (`C#m`, not `Dbm`, which would need 8 flats).
 */
"musical_standard" | 
/**  rekordbox's own spelling, from the rekordbox behavior check. */
"musical_rekordbox" | 
/**  Every black key as a sharp: `C#`, `D#m`, `A#`. */
"musical_sharps" | 
/**  Every black key as a flat: `Db`, `Ebm`, `Bb`. */
"musical_flats";

/**  The last export read into the snapshot. */
export type LastRead = {
	path: string,
	/**
	 *  The file's modified time when the read began, in milliseconds since
	 *  the Unix epoch.
	 */
	modifiedMs: number,
	/**  When the snapshot was replaced (UTC, ISO 8601). */
	readAt: string,
	summary: SnapshotSummary,
};

/**  A music folder, as the frontend sees it. */
export type MusicFolder = {
	id: MusicFolderId,
	role: MusicFolderRole,
	/**  Whether the folder's watcher is on (1aC-6). */
	watch: boolean,
	/**
	 *  Where the folder is, e.g. `E:\DJ Music`: under the volume's mount
	 *  point now, or where it was last seen if the volume is offline.
	 */
	path: string,
	/**  Whether its volume is mounted right now. */
	online: boolean,
	/**  The volume's label, e.g. `GIG USB`. May be empty. */
	volumeLabel: string,
	/**  When it was added, UTC ISO-8601. */
	addedAt: string,
	/**
	 *  When a scan last walked the whole folder, UTC ISO-8601. `None` until
	 *  one has.
	 */
	walkedAt: string | null,
	/**
	 *  Folders inside it that the last walk couldn't list (1aB-14). `None`
	 *  until a walk has finished.
	 */
	unreadableFolders: number | null,
	/**
	 *  Audio files in it that the last walk couldn't look at, or whose
	 *  names can't be stored (1aB-14). `None` until a walk has finished.
	 */
	unreadableFiles: number | null,
	/**  Files in it that are online only (OneDrive placeholders, 1aB-8). */
	onlineOnlyFiles: number,
};

/**  A music folder's row id. */
export type MusicFolderId = number;

/**  What a music folder is for. Stored in `music_folder.role`. */
export type MusicFolderRole = 
/**  Scanned into All music (the default). */
"scan" | 
/**  Watched for new arrivals (Phase 2, ROADMAP 2.1). */
"inbox";

/**  An operation, as undo reports it. */
export type OperationInfo = {
	/**
	 *  The operation's row id. Row ids cross IPC as plain numbers (see
	 *  `ipc.rs`).
	 */
	id: number,
	/**
	 *  What kind of action it was, e.g. `edit_fields`. The UI describes it
	 *  from the locale files.
	 */
	kind: string,
};

/**  The last read that failed. The snapshot is unchanged by it. */
export type ReadFailure = {
	path: string,
	reason: FailureReason,
	/**  When it failed (UTC, ISO 8601). */
	at: string,
};

/**  One reason for a suggestion: an i18n key, its parameters and its source. */
export type Reason = {
	/**  An i18n key with its namespace, e.g. `crates:reason.sameKey`. */
	key: string,
	params: { [key in string]: ReasonParam },
	source: ReasonSource,
};

/**
 *  A value filled into a reason's text, e.g. `bpm` = 2 or `tag` = "Peak Time".
 * 
 *  Text parameters are data (a tag name, a title), never prose: the words
 *  around them live in the locale file. Numbers stay numbers so the frontend
 *  formats them for the user's language.
 */
export type ReasonParam = string | number | null;

/**  Where a reason comes from. */
export type ReasonSource = 
/**  A fact from the Library, rekordbox or the files: a key, a BPM, a tag. */
"fact" | 
/**
 *  The audio model's opinion (3.8). Labeled as such in the UI, optional,
 *  and never the only reason.
 */
"audioModel";

/**  A file the walk added to the index, as the frontend hears it. */
export type ScannedFile = {
	/**  The `file` row id. */
	id: number,
	musicFolderId: MusicFolderId,
	/**  From the music folder, `/`-separated, in the on-disk spelling. */
	relPath: string,
	/**  In bytes. */
	size: number,
	/**
	 *  Milliseconds since the Unix epoch (the stored nanoseconds don't fit
	 *  a JavaScript number).
	 */
	modifiedMs: number,
	/**  A OneDrive placeholder: its bytes aren't on this PC. */
	onlineOnly: boolean,
};

/**  Files the walk just added to the index, one batch at a time. */
export type ScannedFiles = ScannedFile[];

/**  What a read did to the snapshot. */
export type SnapshotSummary = {
	/**  Tracks stored from this read, streaming ones included. */
	tracks: number,
	/**  Of those, streaming entries (no file). */
	streaming: number,
	/**  Tracks kept from earlier reads because this export is incomplete. */
	kept: number,
	/**  Tracks in the export that couldn't be stored. */
	notStored: number,
	/**  Whether the export held every track it said it did. */
	complete: boolean,
};

/**
 *  Something the app suggests (`what`), with the reasons it's suggested.
 * 
 *  Always has at least one reason, and at least one that isn't the audio
 *  model's. See the module docs.
 */
export type Suggestion<T> = {
	what: T,
	reasons: Reason[],
};

/**  Something changed since the operation that undo would overwrite. */
export type UndoConflict = {
	entity: string,
	/**  The row's id in `entity`. */
	entityId: number,
	/**  The field that changed since; null when the whole row is at issue. */
	field: string | null,
	problem: ConflictProblem,
};

/**  What undoing the last operation did. */
export type UndoOutcome = 
/**  Every change of the operation was reversed. */
{ status: "undone"; operation: OperationInfo } | 
/**  No operation, or the last one is already undone. */
{ status: "nothingToUndo" } | 
/**  Undoing would overwrite later changes, so nothing was changed. */
{ status: "refused"; operation: OperationInfo; conflicts: UndoConflict[] };

/**  Drives came or went: the music folders' `online` may have changed. */
export type VolumesChanged = null;

/**  Everything the XML source screen shows. */
export type XmlSource = {
	/**  The export the user chose, if any. */
	path: string | null,
	watch: boolean,
	lastRead: LastRead | null,
	/**  Set when the newest read attempt failed. */
	lastFailure: ReadFailure | null,
	/**  With the watch on: an export newer than the last read, to offer. */
	newerExport: ExportFile | null,
	/**  rekordbox's default export folder (Documents), if Windows has one. */
	exportFolder: string | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

