// Regenerate with `cargo run --example export_bindings` in src-tauri.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  Returns the app's name, version and bundle ID. */
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	/**
	 *  The key notation the user chose; Camelot until they choose one. The
	 *  frontend formats keys with it and the generated `KEY_NAMES` table.
	 */
	keyNotation: () => typedError<KeyNotation, IpcError>(__TAURI_INVOKE("key_notation")),
	/**  Sets the key notation for the whole app. */
	setKeyNotation: (notation: KeyNotation) => typedError<null, IpcError>(__TAURI_INVOKE("set_key_notation", { notation })),
	/**  Every queued and running job, for the Activity status to start from. */
	activity: () => typedError<ActivitySnapshot, IpcError>(__TAURI_INVOKE("activity")),
	/**  Cancels a queued or running job. */
	cancelJob: (id: JobId) => typedError<CancelOutcome, IpcError>(__TAURI_INVOKE("cancel_job", { id })),
	/**
	 *  Undoes the newest operation that isn't undone yet, unless something it
	 *  wrote has changed since. With `operation_id`, only if that operation is
	 *  the one to undo. If the undo hits an error, nothing was changed.
	 */
	undoLastOperation: (operationId: number | null) => typedError<UndoOutcome, IpcError>(__TAURI_INVOKE("undo_last_operation", { operationId })),
	/**
	 *  What Undo would undo now, and why it would be refused, if it would.
	 *  Changes nothing.
	 */
	nextUndoOperation: () => typedError<NextUndo, IpcError>(__TAURI_INVOKE("next_undo_operation")),
	/**  Every music folder, oldest first. */
	musicFolders: () => typedError<MusicFolder[], IpcError>(__TAURI_INVOKE("music_folders")),
	/**
	 *  Adds a music folder and scans it: exactly one scan of it is queued
	 *  before this returns, whichever screen asked, and shows in Activity.
	 *  `role` defaults to scan.
	 */
	addMusicFolder: (path: string, role: 
/**  Scanned into All music (the default). */
"scan" | 
/**  Watched for new arrivals (Phase 2, ROADMAP 2.1). */
"inbox" | null) => typedError<MusicFolder, IpcError>(__TAURI_INVOKE("add_music_folder", { path, role })),
	/**  Removes a music folder from the app. Its files stay on disk untouched. */
	removeMusicFolder: (id: MusicFolderId) => typedError<null, IpcError>(__TAURI_INVOKE("remove_music_folder", { id })),
	/**
	 *  Scans the music folders `ids`, or all of them. Returns the job's id; its
	 *  progress shows in Activity, and new files arrive as `ScannedFiles`.
	 *  Asked again while that same scan is waiting, nothing more is queued and
	 *  the waiting job's id comes back; while it's running, it runs once more
	 *  when it ends, however many times it's asked (a double click is one
	 *  scan).
	 */
	scanMusicFolders: (ids: MusicFolderId[] | null) => typedError<JobId, IpcError>(__TAURI_INVOKE("scan_music_folders", { ids })),
	/**
	 *  Turns a music folder's watcher on or off. On: the folder is rescanned
	 *  now and whenever files change under it while the app runs. Off (the
	 *  default): it's still rechecked at app start and when its drive comes
	 *  back, and otherwise scanned when asked.
	 */
	setMusicFolderWatch: (id: MusicFolderId, watch: boolean) => typedError<null, IpcError>(__TAURI_INVOKE("set_music_folder_watch", { id, watch })),
	/**
	 *  The rekordbox XML source: the chosen export, the watch, the last read or
	 *  failure and, with the watch on, a newer export to offer.
	 */
	rekordboxXmlSource: () => typedError<XmlSource, IpcError>(__TAURI_INVOKE("rekordbox_xml_source")),
	/**
	 *  Reads an export into the snapshot, as a job. With a `path` (the file
	 *  the user just picked, or a newer export offered), that file becomes the
	 *  chosen export once it's read; without one, the chosen export is read
	 *  again. Returns the job's id.
	 */
	readRekordboxXml: (path: string | null) => typedError<JobId, IpcError>(__TAURI_INVOKE("read_rekordbox_xml", { path })),
	/**  Turns the watch for newer exports on or off. */
	setRekordboxXmlWatch: (watch: boolean) => typedError<null, IpcError>(__TAURI_INVOKE("set_rekordbox_xml_watch", { watch })),
	/**
	 *  Whether the app may read (and so download) online-only files. Off until
	 *  the user turns it on.
	 */
	readOnlineOnlyFiles: () => typedError<boolean, IpcError>(__TAURI_INVOKE("read_online_only_files")),
	/**  Lets the app read online-only files, or stops it. */
	setReadOnlineOnlyFiles: (on: boolean) => typedError<null, IpcError>(__TAURI_INVOKE("set_read_online_only_files", { on })),
	/**
	 *  Hashes the files in the music folders `ids`, or in all of them, that
	 *  have no hashes yet or changed since they were hashed. Returns the job's
	 *  id; it runs in the background at low priority, and its progress shows
	 *  in Activity.
	 */
	hashMusicFolders: (ids: MusicFolderId[] | null) => typedError<JobId, IpcError>(__TAURI_INVOKE("hash_music_folders", { ids })),
	/**
	 *  Reads the files in the music folders `ids`, or in all of them. Returns
	 *  the job's id; its progress shows in Activity.
	 */
	readFiles: (ids: MusicFolderId[] | null) => typedError<JobId, IpcError>(__TAURI_INVOKE("read_files", { ids })),
	/**
	 *  Fingerprints every file that's due, in the background. Returns the
	 *  job's id; if a fingerprint job over every file is already queued or
	 *  running, returns that one instead of starting another.
	 */
	fingerprintFiles: () => typedError<JobId, IpcError>(__TAURI_INVOKE("fingerprint_files")),
	/**
	 *  Fingerprints `file_ids` before anything else: the tracks on screen.
	 *  A running fingerprint job takes them next; if none is running, a job
	 *  for just these starts at once, and its id is returned.
	 */
	fingerprintFirst: (fileIds: number[]) => typedError<number | null, IpcError>(__TAURI_INVOKE("fingerprint_first", { fileIds })),
	/**
	 *  Matches rekordbox tracks to files again, in the background. Returns the
	 *  job's id; if a relink is already waiting to run, returns that one.
	 */
	relinkRekordboxTracks: () => typedError<JobId, IpcError>(__TAURI_INVOKE("relink_rekordbox_tracks")),
	/**
	 *  Groups every file into tracks, in the background. Returns the job's id;
	 *  if a grouping job is already queued, returns that one instead of
	 *  starting another. If one is running (it may have loaded the files
	 *  already), it's asked to run once more when it ends, like the chained
	 *  stages are ([`crate::scan::chain::queue_once`]).
	 */
	groupFiles: () => typedError<JobId, IpcError>(__TAURI_INVOKE("group_files")),
	/**
	 *  The rekordbox tracks that have no file, by last known folder, with an
	 *  offer to add each folder that exists now (1aD-5).
	 */
	missingTracks: () => typedError<MissingList, IpcError>(__TAURI_INVOKE("missing_tracks")),
	/**  Every Library track, sorted for the Library list (see [`list`]). */
	libraryTracks: () => typedError<LibraryTrack[], IpcError>(__TAURI_INVOKE("library_tracks")),
	/**
	 *  Adds a track to the Library as a linked Library track. Its file is never
	 *  written. Adding a track that's already there changes nothing.
	 */
	promoteTrack: (recordingId: number) => typedError<Promoted, IpcError>(__TAURI_INVOKE("promote_track", { recordingId })),
	/**
	 *  Removes a track from the Library. Only the Library track goes: the
	 *  file on disk is never touched, and undo brings it back.
	 */
	removeLibraryTrack: (id: LibraryTrackId) => typedError<null, IpcError>(__TAURI_INVOKE("remove_library_track", { id })),
	/**
	 *  How many rekordbox tracks could be added to the Library, and how many
	 *  are left out and why. With `playlists`, only the tracks in those
	 *  rekordbox playlists. Changes nothing.
	 */
	rekordboxOffer: (playlists: string[][] | null) => typedError<Offer, IpcError>(__TAURI_INVOKE("rekordbox_offer", { playlists })),
	/**
	 *  Adds the offered rekordbox tracks to the Library as linked Library
	 *  tracks, as one undoable operation. No file is written. With `playlists`,
	 *  only the tracks in those rekordbox playlists; the playlists themselves
	 *  aren't imported and the pick isn't remembered.
	 */
	addRekordboxTracks: (playlists: string[][] | null) => typedError<AddSummary, IpcError>(__TAURI_INVOKE("add_rekordbox_tracks", { playlists })),
	/**  Undoes an add of rekordbox tracks, if nothing else was done since. */
	undoAddRekordboxTracks: (operationId: number) => typedError<UndoOutcome, IpcError>(__TAURI_INVOKE("undo_add_rekordbox_tracks", { operationId })),
	/**  The rekordbox playlists that hold tracks, for narrowing the offer. */
	rekordboxPlaylists: () => typedError<PlaylistChoice[], IpcError>(__TAURI_INVOKE("rekordbox_playlists")),
	/**
	 *  The tracks in All music whose title, artist or file path holds `search`
	 *  (every track when it's blank), up to 200, with whether each is in the
	 *  Library.
	 */
	allMusicTracks: (search: string | null) => typedError<AllMusicList, IpcError>(__TAURI_INVOKE("all_music_tracks", { search })),
	/**
	 *  Where the send is: the file's path, the preflight waiting for the go,
	 *  and how the last step ended.
	 */
	sendState: () => typedError<SendState, IpcError>(__TAURI_INVOKE("send_state")),
	/**
	 *  Starts a send: reads rekordbox's export again and builds the preflight,
	 *  as a job. With a `path`, that file is read and becomes the chosen
	 *  export; without one, the chosen export is read. Any earlier preflight
	 *  is dropped at once. Returns the job's id.
	 */
	prepareSend: (path: string | null) => typedError<JobId, IpcError>(__TAURI_INVOKE("prepare_send", { path })),
	/**
	 *  The user's go: writes the send the preflight `token` names and records
	 *  it, as a job. `confirmed` is the explicit confirm
	 *  ([`Preflight::needs_confirm`] says when it's needed). Returns the job's id; the job refuses
	 *  anything that isn't exactly the reviewed send.
	 */
	writeSend: (token: string, confirmed: boolean) => typedError<JobId, IpcError>(__TAURI_INVOKE("write_send", { token, confirmed })),
	/**
	 *  The stale playlists and the manual removals, from the database as it is
	 *  now. Reads only.
	 */
	afterSendLists: () => typedError<AfterSendLists, IpcError>(__TAURI_INVOKE("after_send_lists")),
	/**  Makes a crate. The name is trimmed. */
	createCrate: (name: string) => typedError<CrateId, IpcError>(__TAURI_INVOKE("create_crate", { name })),
	/**
	 *  Renames a crate. Answers the operation recorded, or none when the name
	 *  is the one it has.
	 */
	renameCrate: (id: CrateId, name: string) => typedError<number | null, IpcError>(__TAURI_INVOKE("rename_crate", { id, name })),
	/**  Deletes a crate. Its Library tracks stay in the Library. */
	deleteCrate: (id: CrateId) => typedError<null, IpcError>(__TAURI_INVOKE("delete_crate", { id })),
	/**  Adds Library tracks to a crate. A track that's in it already is skipped. */
	addTracksToCrate: (id: CrateId, tracks: LibraryTrackId[]) => typedError<Changed, IpcError>(__TAURI_INVOKE("add_tracks_to_crate", { id, tracks })),
	/**  Takes tracks out of a crate. They stay in the Library. */
	removeTracksFromCrate: (id: CrateId, tracks: LibraryTrackId[]) => typedError<Changed, IpcError>(__TAURI_INVOKE("remove_tracks_from_crate", { id, tracks })),
	/**  Every crate with its track count. */
	listCrates: () => typedError<Crate[], IpcError>(__TAURI_INVOKE("list_crates")),
	/**  A crate's tracks, in the order they were added. */
	crateTracks: (id: CrateId) => typedError<LibraryTrack[], IpcError>(__TAURI_INVOKE("crate_tracks", { id })),
};

/** Events */
export const events = {
	jobUpdates: makeEvent<JobUpdates>("job-updates"),
	scannedFiles: makeEvent<ScannedFiles>("scanned-files"),
	volumesChanged: makeEvent<VolumesChanged>("volumes-changed"),
};

/* Constants */
export const ERROR_KEYS = {"alreadyAdded":"musicFolders:alreadyAdded","badPath":"musicFolders:badPath","busy":"errors:busy","cannotWrite":"errors:cannotWrite","containsMusicFolder":"musicFolders:containsMusicFolder","crateNameEmpty":"crates:error.nameEmpty","crateNameTaken":"crates:error.nameTaken","crateNameUnsendable":"crates:error.nameUnsendable","crateNotFound":"crates:error.notFound","damaged":"errors:damaged","database":"errors:database","diskFull":"errors:diskFull","insideMusicFolder":"musicFolders:insideMusicFolder","internal":"errors:internal","libraryFileMissing":"library:error.fileMissing","libraryMatchNotConfirmed":"library:error.matchNotConfirmed","libraryNoFile":"library:error.noFile","libraryTrackNotFound":"library:error.trackNotFound","musicFolderInUse":"musicFolders:inUse","musicFolderNotFound":"musicFolders:notFound","noRekordboxXml":"rekordbox:error.noneChosen","notAFolder":"musicFolders:notAFolder","notRekordboxXml":"rekordbox:error.notAnExport","rekordboxXmlNotFound":"rekordbox:error.notFound","stopped":"errors:stopped"} as const;

export const KEY_NAMES = [{"names":["1A","2A","3A","4A","5A","6A","7A","8A","9A","10A","11A","12A","1B","2B","3B","4B","5B","6B","7B","8B","9B","10B","11B","12B"],"notation":"camelot"},{"names":["G#m","Ebm","Bbm","Fm","Cm","Gm","Dm","Am","Em","Bm","F#m","C#m","B","F#","Db","Ab","Eb","Bb","F","C","G","D","A","E"],"notation":"musical_standard"},{"names":["Abm","Ebm","Bbm","Fm","Cm","Gm","Dm","Am","Em","Bm","F#m","Dbm","B","F#","Db","Ab","Eb","Bb","F","C","G","D","A","E"],"notation":"musical_rekordbox"},{"names":["G#m","D#m","A#m","Fm","Cm","Gm","Dm","Am","Em","Bm","F#m","C#m","B","F#","C#","G#","D#","A#","F","C","G","D","A","E"],"notation":"musical_sharps"},{"names":["Abm","Ebm","Bbm","Fm","Cm","Gm","Dm","Am","Em","Bm","Gbm","Dbm","B","Gb","Db","Ab","Eb","Bb","F","C","G","D","A","E"],"notation":"musical_flats"}] as const;

/* Types */
/**
 *  Every queued and running job, and the `seq` of the last update already
 *  reflected in it.
 */
export type ActivitySnapshot = {
	seq: number,
	/**  Running jobs first, then queued; each in the order workers take them. */
	jobs: JobUpdate[],
};

/**  What an add did. */
export type AddSummary = {
	/**  Library tracks made. */
	added: number,
	alreadyInLibrary: number,
	waitingInMissing: number,
	waitingForConfirmation: number,
	/**
	 *  The operation that added them, for [`undo_add`]. `None` when nothing
	 *  was added.
	 */
	operationId: number | null,
};

/**  Both lists, for the screen. */
export type AfterSendLists = {
	/**
	 *  Whether rekordbox's playlists are known: false until a read made
	 *  since this list existed, so an empty `stale_playlists` isn't read as
	 *  "nothing to delete" when nothing was checked.
	 */
	playlistsChecked: boolean,
	stalePlaylists: StalePlaylist[],
	manualRemovals: ManualRemoval[],
};

/**  The tracks matching a search, up to [`LIST_LIMIT`] of them. */
export type AllMusicList = {
	/**  How many tracks match, shown or not. */
	total: number,
	tracks: AllMusicTrack[],
};

/**  A track in All music. */
export type AllMusicTrack = {
	/**  The track's id, as "Add to Library" takes it. */
	recordingId: number,
	/**
	 *  The title shown: the track's own, else what a send would write for
	 *  it, else the file's name. `None` only when the track has no file.
	 */
	title: string | null,
	artist: string | null,
	/**
	 *  The file adding it to the Library would link (ROADMAP 1.8), or
	 *  otherwise its best file, or its first.
	 */
	file: LinkedFile | null,
	inLibrary: boolean,
	/**
	 *  One of its files is the probable match of a rekordbox track, and
	 *  the match can't be confirmed yet: it can't be added to the Library
	 *  ([`library::match_not_confirmed`]). The row says so and its "Add
	 *  to Library" is greyed out.
	 */
	matchNotConfirmed: boolean,
};

/**  The app's name, version and bundle ID, as the frontend sees them. */
export type AppInfo = {
	name: string,
	version: string,
	identifier: string,
};

/**  What asking to cancel a job did. */
export type CancelOutcome = 
/**  It hadn't started, and now never will. */
"cancelled" | 
/**  It's running and will stop at its next check. */
"stopping" | 
/**  It had already finished, or there's no such job. */
"not_active";

/**  What adding tracks to a crate, or removing them, did. */
export type Changed = {
	/**  How many tracks were added or removed. */
	changed: number,
	/**
	 *  How many were left alone: already in the crate when adding, not in it
	 *  when removing.
	 */
	skipped: number,
	/**
	 *  The operation this recorded; `None` when nothing changed. Undo is
	 *  offered only for a recorded operation: with none, undo would take
	 *  back an earlier, unrelated one.
	 */
	operationId: number | null,
};

export type ConflictProblem = 
/**  The field holds a different value from the one the operation left. */
"changedSince" | 
/**  The row the operation changed or made has been deleted since. */
"rowGone" | 
/**  The row the operation deleted exists again. */
"rowBack" | 
/**
 *  Other rows now reference the row, and undoing would silently delete
 *  or change them through a foreign key.
 */
"referenced" | 
/**
 *  The database's own rules refuse the earlier value now: another row
 *  holds a name that must be unique, or rows that must not lose this
 *  one point at it.
 */
"blocked";

/**  A crate, as the Crates screen lists it. */
export type Crate = {
	id: CrateId,
	name: string,
	trackCount: number,
};

/**  A crate's row id. */
export type CrateId = number;

/**
 *  What went wrong, in terms the user can act on. Each kind has one
 *  message in the locale files.
 */
export type ErrorKind = 
/**  The database was busy with another write for too long. */
"busy" | 
/**  The disk holding the app data folder is full. */
"diskFull" | 
/**  The app data folder can't be written (read-only, or no permission). */
"cannotWrite" | 
/**  The database file is damaged, or isn't a database. */
"damaged" | 
/**  Any other database failure. */
"database" | 
/**  The database writer has stopped; only a restart brings it back. */
"stopped" | 
/**  A bug or an impossible state: the app did something it shouldn't. */
"internal" | 
/**  The path given as a music folder isn't a folder that exists. */
"notAFolder" | 
/**
 *  The path can't be stored as a music folder: not a full path from a
 *  drive or share, a name Windows doesn't allow, or an unreadable drive.
 */
"badPath" | 
/**  That folder is already a music folder. */
"alreadyAdded" | 
/**  The folder is inside the existing music folder `musicFolder`. */
"insideMusicFolder" | 
/**  The folder contains the existing music folder `musicFolder`. */
"containsMusicFolder" | 
/**  There's no music folder with that id. */
"musicFolderNotFound" | 
/**
 *  Tracks, Library tracks or relinks still use files in the music
 *  folder, so it can't be removed.
 */
"musicFolderInUse" | 
/**  The rekordbox export isn't a file that exists. */
"rekordboxXmlNotFound" | 
/**  The file isn't a rekordbox collection export. */
"notRekordboxXml" | 
/**  No rekordbox export has been chosen yet. */
"noRekordboxXml" | 
/**  There's no track with that id to add to the Library. */
"libraryTrackNotFound" | 
/**  The track has no file to link a Library track to. */
"libraryNoFile" | 
/**  The file the Library track would link to isn't on disk. */
"libraryFileMissing" | 
/**
 *  The track's match to a rekordbox track is only probable, and can't
 *  be confirmed yet.
 */
"libraryMatchNotConfirmed" | 
/**  There's no crate with that id. */
"crateNotFound" | 
/**  The crate's name is empty. */
"crateNameEmpty" | 
/**
 *  Another crate already has the name (names that differ only in letter
 *  case or trailing space count as the same); `name` is that crate's.
 */
"crateNameTaken" | 
/**  The name has a character that can't be sent to rekordbox. */
"crateNameUnsendable";

/**
 *  A value filled into an error message: data (a name, a path, a count),
 *  never prose. Numbers stay numbers so the frontend formats them. They're
 *  32-bit whole numbers, so every one is exact in a TypeScript `number` and
 *  there's no NaN to send; add a finite decimal when a message needs one.
 */
export type ErrorParam = string | number;

/**  An export file found on disk. */
export type ExportFile = {
	path: string,
	/**  The file name, for showing. */
	name: string,
	/**  Milliseconds since the Unix epoch. */
	modifiedMs: number,
};

/**  The export a preflight was made from. */
export type ExportRead = {
	path: string,
	/**
	 *  When rekordbox saved it: the file's modified time, in milliseconds
	 *  since the Unix epoch.
	 */
	modifiedMs: number,
	/**  When the app read it (UTC, ISO 8601). */
	readAt: string,
	/**
	 *  Tracks in the export that couldn't be read. Above 0, the send
	 *  needs an explicit confirm ([`Preflight::needs_confirm`]).
	 */
	notStored: number,
};

/**  Why a read failed, in terms the user can act on. */
export type FailureReason = 
/**  The file isn't there any more. */
"notFound" | 
/**  The file couldn't be opened or read. */
"cantRead" | 
/**  Not well-formed: cut off, or damaged. Export again. */
"damaged" | 
/**  Well-formed XML, but not a rekordbox collection export. */
"notAnExport";

/**
 *  Why a file's location is fragile. The Library shows each with its
 *  reason (the wording lives in the locale files).
 */
export type FragileReason = "downloads" | "temp" | "external" | "network";

/**
 *  Why a command failed, as the frontend receives it: a kind and the
 *  parameters its message needs. Never error text.
 */
export type IpcError = {
	kind: ErrorKind,
	params: { [key in string]: ErrorParam },
};

/**  A job's row id in the `job` table. */
export type JobId = number;

/**
 *  The kinds of background work (ROADMAP 0.1). Stored in `job.kind` as
 *  [`JobKind::as_str`].
 */
export type JobKind = 
/**  Walk the music folders for audio files (1.1). */
"scan" | 
/**  Read the files' tags and audio properties (1.1 stage 2). */
"read" | 
/**  Hash a file's audio (`audio_hash`). */
"hash" | 
/**  Acoustic fingerprint (1.4). */
"fingerprint" | 
/**  Put files into tracks (provisional, 1bC-1 replaces the rule). */
"group" | 
/**  Estimate BPM, key and energy (3.7). */
"analyze" | 
/**  Run the audio model (3.8). */
"embed" | 
/**  Make a Library copy in another format (2.6). */
"convert" | 
/**  Write an export, e.g. the rekordbox XML (1.9). */
"export" | 
/**  Read rekordbox's XML export into the snapshot (1.2). */
"read_rekordbox" | 
/**  Match rekordbox tracks to files (1.2 relink). */
"relink" | 
/**  Attach rekordbox's BPM and key to tracks (1.2, 1aD-4). */
"attach" | 
/**
 *  Measure a file's spectral cutoff, decoded duration and decode
 *  errors (1.6).
 */
"quality";

/**
 *  Where a job is in its life. Stored in `job.status` as
 *  [`JobStatus::as_str`].
 */
export type JobStatus = 
/**  Waiting for a worker. */
"queued" | 
/**  A worker is doing it. */
"running" | 
/**  Finished its work. */
"done" | 
/**  Stopped with an error, kept in `job.error`. */
"failed" | 
/**  Stopped because it was cancelled. */
"cancelled";

/**
 *  A job changed: it was queued, started, made progress or finished.
 * 
 *  Every update carries `seq`, which rises by one with each change the app
 *  makes to any job. A listener that starts from an [`ActivitySnapshot`]
 *  applies only the updates newer than the snapshot's `seq`, and for each
 *  job only updates newer than the last it applied, so a job never goes
 *  back to an older state.
 */
export type JobUpdate = {
	seq: number,
	id: JobId,
	kind: JobKind,
	status: JobStatus,
	/**  0 to 1, once the job has reported any. */
	progress: number | null,
	/**  Higher runs first. */
	priority: number,
};

/**
 *  Job updates, sent together: the newest update for each job that
 *  changed since the last batch, in `seq` order.
 */
export type JobUpdates = JobUpdate[];

/**
 *  How keys are shown: one app-wide setting (ROADMAP §1.1), stored in the
 *  `setting` table (see `crate::settings`). Camelot is the default.
 * 
 *  To add a notation (e.g. Open Key, or Serato's or Mixed In Key's
 *  spellings): add a variant here and to [`KeyNotation::ALL`], and a match
 *  arm in [`MusicalKey::format`]. The stored name, the TypeScript type and
 *  the frontend's name table follow from those.
 */
export type KeyNotation = 
/**  `8A`, `12B`. */
"camelot" | 
/**
 *  Conventional key-signature spelling: the enharmonic name with the
 *  fewest sharps or flats (`C#m`, not `Dbm`, which would need 8 flats).
 */
"musical_standard" | 
/**  rekordbox's own spelling, from the rekordbox behavior check. */
"musical_rekordbox" | 
/**  Every black key as a sharp: `C#`, `D#m`, `A#`. */
"musical_sharps" | 
/**  Every black key as a flat: `Db`, `Ebm`, `Bb`. */
"musical_flats";

/**  The last export read into the snapshot. */
export type LastRead = {
	path: string,
	/**
	 *  The file's modified time when the read began, in milliseconds since
	 *  the Unix epoch.
	 */
	modifiedMs: number,
	/**  When the snapshot was replaced (UTC, ISO 8601). */
	readAt: string,
	summary: SnapshotSummary,
};

/**  A Library track a send leaves out. */
export type LeftOut = {
	track: TrackLabel,
	reason: LeftOutReason,
	/**  The rekordbox field at fault, where the reason names one. */
	attribute: string | null,
};

/**
 *  Why a Library track is left out of a send. A code; the wording is in
 *  the locale file.
 */
export type LeftOutReason = 
/**  It has no linked file. */
"noFile" | 
/**  Its linked file isn't on disk. */
"fileMissing" | 
/**
 *  Its file's path can't be worked out (its drive or folder doesn't
 *  read back).
 */
"noPath" | 
/**  Its path can't be written as a rekordbox `Location`. */
"pathNotSendable" | 
/**
 *  One of its values holds a character XML can't carry
 *  ([`LeftOut::attribute`] names the field).
 */
"unsendableCharacter" | 
/**  An earlier track of this send is the same file. */
"sameFileAsAnother" | 
/**
 *  rekordbox's own entry for it can't be sent back as it is (its
 *  `TrackID` or an attribute is unusable or repeated).
 */
"rekordboxEntry";

/**  A Library track, with what the Library list shows. */
export type LibraryTrack = {
	id: LibraryTrackId,
	/**  The track (`recording`) it was made from. */
	recordingId: number,
	kind: LibraryTrackKind,
	/**
	 *  The title and artist the list shows: what a send writes for the
	 *  track, else (for the title) the file's name. `None` only when the
	 *  track has neither.
	 */
	title: string | null,
	artist: string | null,
	/**  The linked file. `None` only for a Library track with no file link. */
	file: LinkedFile | null,
	/**
	 *  Why the linked file's location is fragile (Downloads, a temp folder,
	 *  an external or network drive), if it is (1aD-7).
	 */
	fragile: FragileReason | null,
	/**
	 *  Whether the linked file is gone. Kept current by the scan
	 *  (`library_track.source_status`), not worked out when listed.
	 */
	sourceMissing: boolean,
	/**
	 *  How many conflicts with rekordbox are still open for it. Removing
	 *  the track drops them (undo brings them back).
	 */
	openConflicts: number,
	/**  When it was added, UTC ISO-8601. */
	addedAt: string,
};

/**  A Library track's row id. */
export type LibraryTrackId = number;

/**  What a Library track's audio is. Stored in `library_track.kind`. */
export type LibraryTrackKind = 
/**  It points at an existing file, which is never written. */
"linked" | 
/**  A managed copy in the Library folder (Phase 2, ROADMAP 2.6). */
"copy";

/**  The file a linked Library track plays, as the frontend sees it. */
export type LinkedFile = {
	/**
	 *  Where the file is, e.g. `E:\DJ Music\a.mp3`: under its volume's
	 *  mount point now, or where that was last seen if the volume is
	 *  offline.
	 */
	path: string,
	/**  The file's name, e.g. `a.mp3`. */
	name: string,
	/**  Whether the last scan found it on disk (`file.present`). */
	present: boolean,
	/**
	 *  Whether its drive is connected now. A file on an unplugged drive
	 *  stays `present`, and its track isn't missing.
	 */
	driveConnected: boolean,
};

/**
 *  A crate or playlist that will arrive in rekordbox with entries left out
 *  (their tracks aren't sent). Importing it replaces rekordbox's playlist
 *  of that name, so those entries are lost there (§5.2).
 */
export type LosesEntries = {
	kind: TreeKind,
	/**  The folder names down to it, below `Crates` or `Playlists`. */
	path: string[],
	/**  How many of its entries are left out. */
	lost: number,
	/**  How many entries it has in the app. */
	entries: number,
};

/**  A removed track to remove in rekordbox by hand. */
export type ManualRemoval = {
	recordingId: number,
	/**
	 *  What rekordbox shows for it if it has a row at the sent `Location`,
	 *  else the file's tags, else the file's name ([`shown_removed`]).
	 */
	title: string | null,
	artist: string | null,
	/**
	 *  Where it was sent, as Windows writes it, so the user can find it in
	 *  rekordbox; for a track that was never sent, where rekordbox's own
	 *  entry for it is. `None` if the sent `Location` can't be read back: the row
	 *  then shows only the track's name, and leaves the list once a read made
	 *  after the removal has no row matched to the track.
	 */
	path: string | null,
	/**  When the user removed it, UTC ISO-8601. */
	removedAt: string,
};

/**  The missing tracks that were last in one folder. */
export type MissingGroup = {
	/**
	 *  The last known folder, as Windows writes it. `None` for tracks whose
	 *  Location couldn't be decoded.
	 */
	folder: string | null,
	/**
	 *  Whether the folder exists now and is outside every music folder, so
	 *  adding it as a music folder (`add_music_folder`) makes sense.
	 */
	canAdd: boolean,
	tracks: MissingTrack[],
};

export type MissingList = {
	total: number,
	/**  By folder, in folder order; tracks with no known folder last. */
	groups: MissingGroup[],
};

/**  A rekordbox track with no file. */
export type MissingTrack = {
	/**  The row's id, for the app. Not rekordbox's TrackID. */
	id: number,
	title: string,
	artist: string,
	/**
	 *  Where rekordbox last had the file, as Windows writes it. `None` if
	 *  the Location couldn't be decoded.
	 */
	lastKnownPath: string | null,
};

/**  A music folder, as the frontend sees it. */
export type MusicFolder = {
	id: MusicFolderId,
	role: MusicFolderRole,
	/**  Whether the folder's watcher is on (1aC-6). */
	watch: boolean,
	/**
	 *  Where the folder is, e.g. `E:\DJ Music`: under the volume's mount
	 *  point now, or where it was last seen if the volume is offline.
	 */
	path: string,
	/**  Whether its volume is mounted right now. */
	online: boolean,
	/**  The volume's label, e.g. `GIG USB`. May be empty. */
	volumeLabel: string,
	/**  When it was added, UTC ISO-8601. */
	addedAt: string,
	/**
	 *  When a scan last walked the whole folder, UTC ISO-8601. `None` until
	 *  one has.
	 */
	walkedAt: string | null,
	/**
	 *  Folders inside it that the last walk couldn't list (1aB-14). `None`
	 *  until a walk has finished.
	 */
	unreadableFolders: number | null,
	/**
	 *  Audio files in it that the last walk couldn't look at, or whose
	 *  names can't be stored (1aB-14). `None` until a walk has finished.
	 */
	unreadableFiles: number | null,
	/**  Files in it that are online only (OneDrive placeholders, 1aB-8). */
	onlineOnlyFiles: number,
};

/**  A music folder's row id. */
export type MusicFolderId = number;

/**  What a music folder is for. Stored in `music_folder.role`. */
export type MusicFolderRole = 
/**  Scanned into All music (the default). */
"scan" | 
/**  Watched for new arrivals (Phase 2, ROADMAP 2.1). */
"inbox";

/**  What Undo would do now. */
export type NextUndo = {
	/**  The operation Undo would take back; none when nothing is left. */
	operation: OperationInfo | null,
	/**
	 *  Why it would be refused, when that's known. `None` doesn't promise
	 *  the undo will work: a very large operation isn't tried ahead of time
	 *  (see [`TRIED_AHEAD_UP_TO`]).
	 */
	refusal: UndoRefusal | null,
};

/**  What the offer holds now. */
export type Offer = {
	/**  Tracks the add would put in the Library. */
	toAdd: number,
	/**  Tracks with a trusted match that are in the Library already. */
	alreadyInLibrary: number,
	/**  rekordbox entries with no file: waiting in Review's Missing list. */
	waitingInMissing: number,
	/**  rekordbox entries whose match is still probable. */
	waitingForConfirmation: number,
};

/**
 *  What the UI needs to name an operation, read from its `details`. Each
 *  is there only if the operation recorded it.
 */
export type OperationDetails = {
	/**  The crate's name (after a rename, the new one). */
	name: string | null,
	/**  A renamed crate's name before. */
	from: string | null,
	/**  How many tracks the operation added or removed. */
	tracks: number | null,
};

/**  An operation, as undo reports it. */
export type OperationInfo = {
	/**
	 *  The operation's row id. Row ids cross IPC as plain numbers (see
	 *  `ipc.rs`).
	 */
	id: number,
	/**
	 *  What kind of action it was, e.g. `edit_fields`. The UI describes it
	 *  from the locale files.
	 */
	kind: string,
	details: OperationDetails,
};

/**
 *  A Library track whose linked file rekordbox doesn't have, while it
 *  already has another file of the same track: sending adds a second
 *  rekordbox entry.
 */
export type OtherFile = {
	track: TrackLabel,
	/**  The Library track's file, which the send adds. */
	libraryFile: string | null,
	/**  The file rekordbox already has. */
	rekordboxFile: string | null,
};

/**
 *  A rekordbox playlist to pick, with how many of its entries are tracks
 *  with a file or a last known path (streaming entries aren't counted).
 */
export type PlaylistChoice = {
	path: string[],
	tracks: number,
};

/**  What a send would do, worked out without writing anything. */
export type Preflight = {
	/**  Names this preflight; the write must be given it back. */
	token: string,
	export: ExportRead,
	/**  Tracks rekordbox doesn't have yet. No dialog for these. */
	newTracks: number,
	/**  Tracks rekordbox already has: one Yes/No dialog each on import. */
	knownTracks: number,
	leftOut: LeftOut[],
	/**
	 *  Tracks rekordbox has whose file is missing: sent all the same, as
	 *  rekordbox's own entry, so the crates naming them stay whole.
	 */
	fileMissing: TrackLabel[],
	otherFile: OtherFile[],
	/**
	 *  Not empty: the send needs an explicit confirm
	 *  ([`Preflight::needs_confirm`] says when it's needed).
	 */
	losesEntries: LosesEntries[],
	/**  Set when the send can't go at all. */
	refusal: Refusal | null,
	/**
	 *  No track would be sent and there's no crate or playlist: the send
	 *  can't be started.
	 */
	nothingToSend: boolean,
	/**
	 *  Whether the user's go can start the write: the send isn't refused
	 *  and there's something to send.
	 */
	canSend: boolean,
	/**
	 *  Whether the go needs the explicit confirm: a crate or playlist
	 *  loses entries, or the read couldn't store some of rekordbox's
	 *  tracks (a Library track on such a track's file would be sent as
	 *  new, and a Yes in rekordbox would overwrite that entry).
	 */
	needsConfirm: boolean,
};

/**  What adding a track to the Library did. */
export type Promoted = {
	libraryTrack: LibraryTrack,
	/**  False when the track was already in the Library: nothing changed. */
	added: boolean,
};

/**  The last read that failed. The snapshot is unchanged by it. */
export type ReadFailure = {
	path: string,
	reason: FailureReason,
	/**  When it failed (UTC, ISO 8601). */
	at: string,
};

/**  One reason for a suggestion: an i18n key, its parameters and its source. */
export type Reason = {
	/**  An i18n key with its namespace, e.g. `crates:reason.sameKey`. */
	key: string,
	params: { [key in string]: ReasonParam },
	source: ReasonSource,
};

/**
 *  A value filled into a reason's text, e.g. `bpm` = 2 or `tag` = "Peak Time".
 * 
 *  Text parameters are data (a tag name, a title), never prose: the words
 *  around them live in the locale file. Numbers stay numbers so the frontend
 *  formats them for the user's language.
 */
export type ReasonParam = string | number | null;

/**  Where a reason comes from. */
export type ReasonSource = 
/**  A fact from the Library, rekordbox or the files: a key, a BPM, a tag. */
"fact" | 
/**
 *  The audio model's opinion (3.8). Labeled as such in the UI, optional,
 *  and never the only reason.
 */
"audioModel";

/**  A refused send, explained. */
export type Refusal = {
	reason: RefusalReason,
	/**
	 *  Where in the tree the problem is, from `Crates` or `Playlists`
	 *  down; empty when the reason isn't about the tree.
	 */
	path: string[],
};

/**  Why the whole send is refused. */
export type RefusalReason = 
/**
 *  The export just read doesn't hold every track it says it does, so
 *  some of rekordbox's values would come from an older read.
 */
"incompleteExport" | 
/**
 *  The export just read was saved before the last send was recorded:
 *  it can't hold what that send put in rekordbox, so tracks rekordbox
 *  now has would go out as new. The user exports again.
 */
"exportOlderThanLastSend" | 
/**
 *  Two crates, playlists or folders in one folder share a name (or
 *  names rekordbox may treat as one): one would replace the other.
 */
"sameName" | 
/**  A crate, playlist or folder has no name. */
"noName" | 
/**  A name holds a character XML can't carry. */
"unsendableName" | 
/**  Folders nest too deep. */
"tooDeep" | 
/**  The file couldn't be made (a bug; nothing is written). */
"internal";

/**  A file the walk added to the index, as the frontend hears it. */
export type ScannedFile = {
	/**  The `file` row id. */
	id: number,
	musicFolderId: MusicFolderId,
	/**  From the music folder, `/`-separated, in the on-disk spelling. */
	relPath: string,
	/**  In bytes. */
	size: number,
	/**
	 *  Milliseconds since the Unix epoch (the stored nanoseconds don't fit
	 *  a JavaScript number).
	 */
	modifiedMs: number,
	/**  A OneDrive placeholder: its bytes aren't on this PC. */
	onlineOnly: boolean,
};

/**  Files the walk just added to the index, one batch at a time. */
export type ScannedFiles = ScannedFile[];

/**  Why a step of the send stopped. Nothing was sent. */
export type SendFailure = 
/**  The export couldn't be read; the rekordbox source says why. */
"readFailed" | 
/**  The step was cancelled. */
"cancelled" | 
/**  There's no preflight to send, or not the one named. */
"noPreflight" | 
/**  The export changed, or was read again, after the preflight. */
"exportChanged" | 
/**
 *  The Library changed after the preflight: the send would differ
 *  from what was reviewed.
 */
"libraryChanged" | 
/**  The preflight says the send is refused, or has nothing to send. */
"notSendable" | 
/**  The send needs the explicit confirm and it wasn't given. */
"notConfirmed" | 
/**
 *  The file couldn't be written. The file from the last send is as it
 *  was.
 */
"cantWrite" | 
/**
 *  The file was written but the send couldn't be recorded. The file
 *  from the last send is put back when there was one and it can be;
 *  otherwise the new file stays, unrecorded, until the next send
 *  replaces it.
 */
"cantRecord" | 
/**  The database failed, or a bug. */
"internal";

/**  Everything the checklist shows. */
export type SendState = {
	/**  Goes up each time a step ends, however it ends. */
	revision: number,
	/**  The one file a send writes, replaced every time. */
	filePath: string,
	/**  The export that will be read, if one is chosen. */
	exportPath: string | null,
	/**  The preflight waiting for the go. */
	preflight: Preflight | null,
	/**  The step that ended last, in this run of the app. */
	step: SendStep | null,
	/**  Why the last step stopped, until the next step starts. */
	failure: SendFailure | null,
	/**  The last send of this run of the app, until the next read starts. */
	sent: Sent | null,
};

/**  One of the send's two steps. */
export type SendStep = "prepare" | "write";

/**  A send that went through. */
export type Sent = {
	/**  When it was recorded (UTC, ISO 8601). */
	at: string,
	newTracks: number,
	/**  How many Yes/No dialogs to expect in rekordbox. */
	knownTracks: number,
};

/**  What a read did to the snapshot. */
export type SnapshotSummary = {
	/**  Tracks stored from this read, streaming ones included. */
	tracks: number,
	/**  Of those, streaming entries (no file). */
	streaming: number,
	/**  Tracks kept from earlier reads because this export is incomplete. */
	kept: number,
	/**  Tracks in the export that couldn't be stored. */
	notStored: number,
	/**  Whether the export held every track it said it did. */
	complete: boolean,
};

/**  Whether a stale entry is a folder or a playlist. */
export type StaleKind = "folder" | "playlist";

/**  A playlist or folder in rekordbox that the app doesn't have. */
export type StalePlaylist = {
	/**  Folder names down to it, starting with `Crates` or `Playlists`. */
	path: string[],
	kind: StaleKind,
	/**  For a folder, how many playlists are in it (at any depth). */
	playlistsInside: number,
	/**
	 *  A folder with nothing in it at all (not even a subfolder). A folder
	 *  holding only subfolders has no playlists but isn't empty.
	 */
	empty: boolean,
};

/**
 *  Something the app suggests (`what`), with the reasons it's suggested.
 * 
 *  Always has at least one reason, and at least one that isn't the audio
 *  model's. See the module docs.
 */
export type Suggestion<T> = {
	what: T,
	reasons: Reason[],
};

/**  A Library track, as the preflight's lists name it. */
export type TrackLabel = {
	libraryTrack: LibraryTrackId,
	/**  `None` when the track has none; the list then shows the file's name. */
	title: string | null,
	artist: string | null,
	/**  The linked file's name, e.g. `a.mp3`. */
	fileName: string | null,
};

/**  Whether a node is under `Crates` or `Playlists`. */
export type TreeKind = "crate" | "playlist";

/**  Something changed since the operation that undo would overwrite. */
export type UndoConflict = {
	entity: string,
	/**  The row's id in `entity`. */
	entityId: number,
	/**  The field that changed since; null when the whole row is at issue. */
	field: string | null,
	problem: ConflictProblem,
};

/**  What undoing the newest operation did. */
export type UndoOutcome = 
/**  Every change of the operation was reversed. */
{ status: "undone"; operation: OperationInfo } | 
/**
 *  No operation is left to undo (or, when one operation was asked for,
 *  it isn't the next to undo).
 */
{ status: "nothingToUndo" } | 
/**  Undoing would overwrite later changes, so nothing was changed. */
{ status: "refused"; operation: OperationInfo; reason: UndoRefusal; conflicts: UndoConflict[] };

/**  Why a step can't be undone, as the UI says it. A code, never text. */
export type UndoRefusal = 
/**  A track the step added has been sent to rekordbox since. */
{ code: "sentSince" } | 
/**  The step would bring back a crate name another crate has now. */
{ code: "crateNameTaken"; name: string } | 
/**  Something the step changed has changed again since. */
{ code: "changedSince" };

/**  Drives came or went: the music folders' `online` may have changed. */
export type VolumesChanged = null;

/**  Everything the XML source screen shows. */
export type XmlSource = {
	/**  The export the user chose, if any. */
	path: string | null,
	watch: boolean,
	lastRead: LastRead | null,
	/**  Set when the newest read attempt failed. */
	lastFailure: ReadFailure | null,
	/**  With the watch on: an export newer than the last read, to offer. */
	newerExport: ExportFile | null,
	/**  rekordbox's default export folder (Documents), if Windows has one. */
	exportFolder: string | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

